---
Name: seo
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverStripers\seo\Extensions\SiteConfigExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        SEORequestProcessor: '%$SilverStripers\seo\Control\SEORequestProcessor'

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - silverstripers/seo:client/dist/styles/bundle.css

SilverStripe\Control\Director:
  rules:
    'robots.txt': 'SilverStripers\seo\Control\RobotsTXTController'
    
---
Name: seo_page
Only:
  moduleexists: silverstripe/cms
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripers\seo\Extensions\SEODataExtension
